### ISSUE TITLE
Pattern match(es) are non-exhaustive     In a lambda abstraction

### ISSUE THREAD

**Issue by smaccoun** [mgsloan/rex#10]
I'm getting the following warning when `[-Wincomplete-uni-patterns]` is turned on for the following function:

```
usernameRegex :: String -> Maybe ()
usernameRegex = [rex|^([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?)$|]
```

The actual error is:

```
Pattern match(es) are non-exhaustive
    In a lambda abstraction:
        Patterns not matched:
            []
            [_]
            [_, _]
            (_:_:_:_:_)
```

I'm not really sure how to go about accounting for those patterns. Any suggestions?

**Comment by mgsloan** [comment]
Hey!  It's cool that you're using this.  I never got around to using it in real world code, probably because I typically prefer an attoparsec or megaparsec parser.

I think this is a bug with rex.  Instead of generating a lambda, it should generate a case statement that handles the unexpected result via an informative error.

Feel free to open a PR, it would look like modifying the code [here](https://github.com/mgsloan/rex/blob/master/Text/Regex/PCRE/Rex.hs#L326) to use `CaseE` instead of `LamE`.

**Comment by mgsloan** [comment]
If you don't feel like opening a PR, I can fix it, it would not take very much work.  I like encouraging PRs and digging into the TH API if you haven't before, though (not sure if that applies to you).  At first the TH API can be daunting, but it becomes straightforward quite quickly.

**Comment by smaccoun** [comment]
Oh cool, yeah I've actually been wanting to learn TH for a while, so maybe this would be a good chance for me to do so. I might have some bandwidth in a few days, so I'll give it my best shot. Hopefully won't require learning too much TH, as I'm very new to it

**Comment by josephcsible** [comment]
> Instead of generating a lambda, it should generate a case statement that handles the unexpected result via an informative error.

Turns out that this isn't necessary either. Since you're using `padRight` to make sure that you get exactly the right number of elements, it can be refactored to be total without there being an error case to handle. I'm going to submit a PR that does this.

**Comment by mgsloan** [comment]
Fixed, thanks to @josephcsible !
